"use client";

import {
  buildBlocksFromElement,
  sanitizeFilename,
  type ExportDocument,
} from "./markdownBlocks";
import { buildExportHtml } from "./exportHtml";
import { buildDocxBlob } from "./exportDocx";

/**
 * The three ways a finished reply leaves the app. Markdown stays a plain text
 * download (an answer is still portable text); PDF and Word render the reply
 * as a document.
 */

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  // Revoking immediately can cancel the download in some browsers.
  setTimeout(() => URL.revokeObjectURL(url), 10_000);
}

/** Shared entry point for documents the assistant generated itself. */
export function triggerFileDownload(blob: Blob, filename: string) {
  triggerDownload(blob, filename);
}

function withExtension(title: string, extension: string): string {
  return `${sanitizeFilename(title)}.${extension}`;
}

/** Document metadata shared by both writers, so the file is self-describing. */
function documentFor(title: string, blocks: ExportDocument["blocks"]): ExportDocument {
  return {
    title,
    meta: `${new Date().toLocaleString()} · Generated by CareerPilot AI Study Hub`,
    blocks,
  };
}

export function downloadMarkdown(content: string, title: string) {
  triggerDownload(
    new Blob([content], { type: "text/markdown;charset=utf-8" }),
    withExtension(title, "md")
  );
}

export async function downloadDocx(
  root: HTMLElement,
  content: string,
  title: string
): Promise<void> {
  const blocks = await safeBlocks(root, content);
  const blob = buildDocxBlob(documentFor(title, blocks));
  triggerDownload(blob, withExtension(title, "docx"));
}

/**
 * "Save as PDF" through the browser's own print pipeline: real text, correct
 * pagination, vector diagrams — and none of a PDF library's weight in the
 * bundle.
 *
 * The window is opened synchronously, before the first `await`: popup blockers
 * only trust a window opened directly inside the click that asked for it, and
 * building the document first would spend that trust.
 */
export function downloadPdf(
  root: HTMLElement,
  content: string,
  title: string
): void {
  const printWindow = window.open("", "_blank", "width=900,height=1200");
  if (!printWindow) {
    throw new Error("Allow pop-ups for this site to save the reply as PDF");
  }

  printWindow.document.write(
    "<!doctype html><title>Preparing PDF…</title><body style=\"font:14px system-ui;padding:24px;color:#444\">Preparing the PDF…</body>"
  );

  void (async () => {
    try {
      const blocks = await safeBlocks(root, content);
      const html = buildExportHtml(documentFor(title, blocks));
      printWindow.document.open();
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.focus();

      // Let fonts and embedded diagrams settle before the print dialog paints.
      await new Promise((resolve) => setTimeout(resolve, 500));
      printWindow.print();

      /*
       * A little while after the print dialog closes, take the helper tab away
       * — it has nothing to show once the PDF is saved, and leaving a blank
       * window behind is its own small bug report.
       */
      setTimeout(() => {
        try {
          printWindow.close();
        } catch {
          /* the user may have taken the tab over; leaving it is fine */
        }
      }, 1500);
    } catch (error) {
      /*
       * Reported, not rethrown: this runs detached from the click (the print
       * window is already open by now), so a rejection here would surface as an
       * unhandled promise rather than anywhere the user could act on it.
       */
      console.error("Reply export: PDF failed", error);
      printWindow.close();
    }
  })();
}

/**
 * Blocks are read from the rendered reply. If that ever fails (an exotic
 * element, a browser quirk), fall back to exporting the Markdown source as a
 * single code block rather than handing the user an empty document.
 */
async function safeBlocks(root: HTMLElement, content: string) {
  try {
    const blocks = await buildBlocksFromElement(root);
    if (blocks.length) return blocks;
  } catch (error) {
    console.error("Reply export: DOM extraction failed, falling back to Markdown", error);
  }
  return [{ kind: "code" as const, text: content, language: "markdown" }];
}
